version: 0.1.{build}
image: Visual Studio 2017

branches:
  only:
    - master

build_script:
  - ps: .\build.ps1 -target=Pack

test_script:
  - ps: .\build.ps1 -target=Test

artifacts:	
  - path: ./artifacts/*.nupkg	
    name: NBomber

deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: iOAkV/7s8hWo8Hnm9j2UR9vJDHPNqsubhTF3HYOGz02iZtKNUNdvZFgfdf47T/Xj
    on:
      branch: master
      appveyor_repo_tag: true