version: '3.4'
services:

  mongo: 
    image: mongo:4.0.3    
    ports:
      - "27017:27017"
  
  influxdb:
    image: "influxdb:1.5.4"        
    ports:
     - "8086:8086"
    environment:
       INFLUXDB_DB: "\"default\""

  grafana:
    image: "grafana/grafana:5.4.3"    
    ports:
     - "3000:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://grafana:6082"
    depends_on:
      - influxdb

  eclipse-mosquitto:
    image: "eclipse-mosquitto:1.6.8"    
    ports:
      - "1883:1883"
      - "9001:9001"